# Generated by Django 3.1.4 on 2020-12-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('photo_url', models.CharField(blank=True, max_length=100)),
                ('instagram_url', models.CharField(blank=True, max_length=100)),
                ('facebook_url', models.CharField(blank=True, max_length=100)),
                ('youtube_url', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
