# Generated by Django 3.1.4 on 2020-12-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201216_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='url',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
