# Generated by Django 3.1.4 on 2020-12-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201216_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bio',
            field=models.TextField(blank=True, default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='facebookUrl',
            field=models.CharField(blank=True, default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='instagramUrl',
            field=models.CharField(blank=True, default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='photoUrl',
            field=models.CharField(blank=True, default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='youtubeUrl',
            field=models.CharField(blank=True, default=None, max_length=100),
            preserve_default=False,
        ),
    ]
