# Generated by Django 3.1.4 on 2020-12-16 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201216_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='facebookUrl',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='instagramUrl',
            new_name='instagram_url',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='photoUrl',
            new_name='photo_url',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='youtubeUrl',
            new_name='youtube_url',
        ),
    ]
